add exit codes run step

diff --git a/.github/workflows/test_suite_ubuntu.yml b/.github/workflows/test_suite_ubuntu.yml
--- a/.github/workflows/test_suite_ubuntu.yml
+++ b/.github/workflows/test_suite_ubuntu.yml
@@ -66,4 +66,10 @@ jobs:
       - name: Test suite
         run: |
           cd tests/build
-          ./test_CAM_interface
+          ./test_CAM_interfaces
+          if [ $? -ne 0 ]; then
+            echo ":: error  ::Tests failed"
+            exit 1
+          else
+            exit 0
+          fi
